---
title: "1 - auto arimax - all models"
author: "Tito Quadri"
date: "2024-05-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(forecast)
library(readr)
library(lubridate)
library(tidyverse)
library(gridExtra)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# Default theme for charts
theme_set(
  theme_bw() +
    theme(  
      plot.title = element_text(face = "bold", size = 14),
      plot.subtitle = element_text(
        face = "italic", size = 10, 
        # colour = "green50"
      )
    )
)

source('../02 Task 2 - Transmission Price/builtin_functions_old/buitin_functions_full_1.R')


```

# Preparation 

## Set fixed values

```{r}
n <- 720 # n<- floor(nrow(df_test)/24) * 24
cut <- as.POSIXct("2023-12-31 23:00:00", tz = "UTC")
```

## Functions

```{r}
# predict one month retraining every day
predict_24_auto <- function(df, target, regressors, 
                            cut = as.POSIXct("2023-12-31 23:00:00", tz = "UTC"),
                            n = 720) {
  train <- df %>% filter(date<= cut) %>% select(all_of(target)) %>% as.vector()
  train<- train[[1]]
  test <- df %>% filter(date> cut) %>% select(all_of(target))%>% as.vector()
  test<- test[[1]]
  xreg_train<- df %>% filter(date<= cut) %>% select(all_of(regressors)) %>% as.matrix()
  xreg_test <- df %>% filter(date> cut) %>% select(all_of(regressors)) %>% as.matrix()
  
  
  
  prediction <- vector(length = n)          # initialize prediction vec
  first_h <- seq(1, n, by = 24)             # i once every 24
  for (i in first_h) {
    # if ((i+23) > nrow(xreg_test)) break  # Stop loop if xreg_test doesn't have enough rows
    
    # fit arima (no drift)
    fit<-auto.arima(train, xreg = xreg_train, allowdrift = FALSE, max.d = 0)  
    prediction[i:(23+i)] <- as.vector(
      predict(object = fit,
              newxreg = xreg_test[i:(i+23),],
              n.ahead = 24
              )[1]$pred
    )
    
    # update variables
    train<-c(train, test[i:(23+i)])
    xreg_train<- rbind(xreg_train, xreg_test[i:(i+23),]) %>% as.matrix()
  }
  
  predictions<-data.frame(
    predict = prediction,
    actual = test[1:n],
    date = select(filter(df, date> cut), date)[1:n,]
  )
  
  predictions<- predictions %>% mutate(resid = actual - predict)
  
  return(predictions)
}

inference<- function(target, df=df, regressors = regressors){
  xreg<- df %>% select(all_of(regressors)) %>% as.matrix()
  y<- df %>% select(all_of(target))
  fit<- auto.arima(y = y, xreg = xreg, allowdrift = FALSE, max.d= 0)
  return(fit)
}


inference_plots<-function(df, fit, target, setting = "predictive"){
  pacf<- pacf(fit$residuals, plot = FALSE)
  pacf <- data.frame(
    pacf = pacf$acf,
    lag = pacf$lag
  )
  
  
  pl <- ggplot(pacf, aes(x = lag, y = pacf)) +
    geom_segment(aes(x = lag, xend = lag, y = 0, yend = pacf)) +
    geom_point() +
    geom_vline(xintercept = 24*(1:5), linetype = "dashed", color = "blue")+
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_hline(yintercept = c(-1.96/sqrt(length(fit$residuals)), 
                              1.96/sqrt(length(fit$residuals))),
               linetype = "dashed", color = "blue")+
    coord_cartesian(xlim = c(1, 30))+
    labs(x = "Lags", y = "PACF", title = "PACF for ARMA model", subtitle = target)
  
  
  filename <- paste0("../05 Final Presentation/ARMA",setting,"/", target, "/pacf.png")
  ggsave(filename = filename, plot = pl, height = 4, width = 6, , create.dir = TRUE)

  
  acf<- acf(fit$residuals, plot = FALSE)
  
  acf <- data.frame(
    acf = acf$acf,
    lag = acf$lag
  )
  
  pl <- ggplot(acf, aes(x = lag, y = acf)) +
    geom_segment(aes(x = lag, xend = lag, y = 0, yend = acf)) +
    geom_point() +
    geom_vline(xintercept = 24*(1:5), linetype = "dashed", color = "blue")+
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_hline(yintercept = c(-1.96/sqrt(length(fit$residuals)), 
                              1.96/sqrt(length(fit$residuals))),
               linetype = "dashed", color = "blue")+
    coord_cartesian(xlim = c(1, 30))+
    labs(x = "Lags", y = "ACF", title = "ACF for ARMA model", subtitle = target)
  
    filename <- paste0("../05 Final Presentation/ARMA",setting,"/",target, "/acf.png")
  ggsave(filename = filename, plot = pl, height = 4, width = 6)
  
  fitted_values <- data.frame(
    fitted = fit$fitted,
    actual = as.vector(select(df, target)), 
    date = df$date
  )
  names(fitted_values)<- c("fitted", "actual", "date")
  
  fitted_values <- fitted_values %>% 
    mutate(residuals = actual - fitted)

  pl <- ggplot(fitted_values, aes(x = fitted, y = residuals)) +
    geom_point() +
    geom_smooth(method = "loess", color = "red") +
    geom_hline(yintercept = mean(fitted_values$residuals_aic), 
               linetype = "dashed", col = 'blue') +
    geom_hline(yintercept = 0, linetype = "dashed") +
    labs(x = "Fitted Values", y = "Residuals", 
         title = "Tukey-Anscombe Plot for ARMA", subtitle = target)
  
    filename <- paste0("../05 Final Presentation/ARMA",setting,"/",target,"/Tukey-Anscombe.png")
  ggsave(filename = filename, plot = pl, height = 4, width = 6)
}

  
# display predicted and actual time series together
graph_predicted<- function(df, title) {
  df %>% 
    ggplot(aes(x= date)) +
    geom_line(aes(y = actual, colour = "Actual", )) +
    geom_line(aes(y = .pred, colour = "Predicted")) +
    labs(title = title,
         y = "price",
         x = NULL,
         colour = NULL) +
    ggsci::scale_colour_jama() +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
          plot.subtitle = element_text(face = "italic", size = 12,
                                       colour = "grey50"),
          legend.position = "bottom")
}

prediction_plots<- function(target, predictions, setting = "predictive"){
  
  pl <- ggplot(predictions, aes(x = predict, y = resid)) +
    geom_point() +
    geom_smooth(method = "loess", color = "red") +
    geom_hline(yintercept = mean(predictions$resid), linetype = "dashed", col = 'red') +
    geom_hline(yintercept = 0, linetype = "dashed") +
    labs(x = "Prediction", y = "Prediction error", title = "Prediction error against Prediction model", subtitle = target)
  filename <- paste0("../05 Final Presentation/ARMA",setting,"/",target,"/Prediction error against Prediction ARMA.png")
  ggsave(filename = filename, plot = pl, height = 4, width = 6, create.dir = TRUE)
  
  pl <- ggplot(predictions, aes(x = date, y = resid)) +
    geom_line() +
    scale_x_datetime(date_labels = "%D", breaks = "3 day") +
    geom_smooth(method = "loess", color = "red") +
    geom_hline(yintercept = mean(predictions$resid), linetype = "dashed", col = 'red') +
    geom_hline(yintercept = 0, linetype = "dashed") +
    labs(x = "Hourly Data", y = "Prediction error", title = "Time series of Prediction errors ARMA", subtitle = target) +
    geom_vline(data = data.frame(date = seq(min(predictions$date), max(predictions$date), by = "week")),
               aes(xintercept = as.numeric(date)), linetype = "dashed", color = "blue")
  filename <- paste0("../05 Final Presentation/ARMA",setting,"/",target,"/Time series of Prediction errors ARMA.png")
  ggsave(filename = filename, plot = pl, height = 4, width = 6)
  
  pl <- ggplot(predictions, aes(x = date)) +
    geom_line(aes(y = predict, col = 'Prediction')) +
    geom_line(aes(y = actual, col = 'Actual')) +
    scale_x_datetime(date_labels = "%D", breaks = "3 day") +
    labs(x = "Hourly data",
         y = "Price",
         color = "Day ahead prices", subtitle = target, title = "Prices and predictions ARMA") +
    scale_color_manual(values = c("Actual" = "grey50", "Prediction" = "firebrick")) +
    theme(plot.margin = margin(10, 10, 10, 10), legend.position = "bottom") +
    geom_vline(data = data.frame(date = seq(min(predictions$date), max(predictions$date), by = "week")),
               aes(xintercept = as.numeric(date)), linetype = "dashed", color = "blue")
  
  filename <- paste0("../05 Final Presentation/ARMA",setting,"/",target,"/Prices and predictions ARMA.png")
  ggsave(filename = filename, plot = pl, height = 4, width = 6)
  
}


```

# Results

## Predictive

### CH price

```{r}

df <- read.csv("../00 Data Retrieval and Cleaning/0_df_predictive_ch_spot_price.csv") %>% mutate(date = ymd_hms(date))
regressors <- c("day_ahead_price_de", "day_ahead_price_fr", "actual_load_ch", "capacity_forecast_de_lu_ch", "solar_ch" ,"crossborder_actual_flow_fr_ch", "nuclear_ch", "nuclear_actual_aggregated_de")
```

```{r}
target <- "day_ahead_price_ch"

pred <- predict_24_auto(df, target, regressors)

prediction_plots(target = target, predictions = pred)

df_pred<- data.frame("date"= pred$date, 
             ".pred" = pred$predict,
             "actual" = pred$actual)

write.csv(x = df_pred, file =  "../01 Task 1 - Spot Price/1 - ARIMAX - Prediction - CH - Data Predictive/holdout_predictions.csv")

```


```{r}

fit<- inference(target, regressors = regressors, df = df)

inference_plots(df = df, fit = fit, target = target)

```

### DE price

```{r}
df<- read.csv("../00 Data Retrieval and Cleaning/0_df_predictive_de_spot_price.csv")  %>% mutate(date = ymd_hms(date))

regressors = c("biomass_actual_aggregated_de", "crossborder_actual_flow_de_lu_ch", "day_ahead_price_fr", "actual_load_de", "fossil_gas_actual_aggregated_de" ,"wind_onshore_actual_aggregated_de", "nuclear_actual_aggregated_de", "other_actual_aggregated_de", "solar_forecast_de")
```

```{r}
target <- "day_ahead_price_de"

pred <- predict_24_auto(df, target, regressors)

prediction_plots(target = target, predictions = pred)

df_pred<- data.frame("date"= pred$date, 
             ".pred" = pred$predict,
             "actual" = pred$actual)

write.csv(df_pred, "../01 Task 1 - Spot Price/1 - ARIMAX - Prediction - DE - Data Predictive/holdout_predictions.csv")
```

### Inference

```{r}

fit<- inference(target, regressors = regressors, df = df)

inference_plots(df = df, fit = fit, target = target)

```

### DECH price

```{r}
df <- read.csv("../00 Data Retrieval and Cleaning/0_df_predictive_dech_auction_price.csv") %>% mutate(date = ymd_hms(date))

regressors = c("day_ahead_price_ch", "day_ahead_price_de", "actual_load_ch", 
               "actual_load_de", "allocated_capacity_de_ch" ,
               "capacity_forecast_de_lu_ch", "crossborder_actual_flow_de_lu_ch", 
               "solar_actual_aggregated_de", "nuclear_actual_aggregated_de",
               "solar_forecast_de")
```

```{r}
target<- "auction_price_de_ch"

pred <- predict_24_auto(df, target, regressors)

pred$predict[pred$predict<0]<-0

prediction_plots(target = target, predictions = pred)

df_pred<- data.frame("date"= pred$date, 
             ".pred" = pred$predict,
             "actual" = pred$actual)

write.csv(df_pred, "../02 Task 2 - Transmission Price/1 - ARIMAX - Prediction - DECH - Data Predictive/holdout_predictions.csv")
```


```{r}

fit<- inference(target, regressors = regressors, df = df)

inference_plots(df = df, fit = fit, target = target)

```

### CHDE price

```{r}
df <- read.csv("../00 Data Retrieval and Cleaning/0_df_predictive_chde_auction_price.csv") %>% mutate(date = ymd_hms(date))

regressors = c("day_ahead_price_ch", "day_ahead_price_de", "actual_load_ch", "actual_load_de", "allocated_capacity_ch_de" ,"capacity_forecast_ch_de_lu", "crossborder_actual_flow_ch_de_lu", "solar_actual_aggregated_de", "nuclear_actual_aggregated_de", "solar_forecast_de")
```

```{r}
target<- "auction_price_ch_de"

pred <- predict_24_auto(df, target, regressors)

pred$predict[pred$predict<0]<-0

prediction_plots(target = target, predictions = pred)

df_pred<- data.frame("date"= pred$date, 
             ".pred" = pred$predict,
             "actual" = pred$actual)

write.csv(df_pred, "../02 Task 2 - Transmission Price/1 - ARIMAX - Prediction - CHDE - Data Predictive/holdout_predictions.csv")
```


```{r}

fit<- inference(target, regressors = regressors, df = df)

inference_plots(df = df, fit = fit, target = target)

```

## Theoretical

### CH price

```{r}
setting <- "theoretical"

df <- read.csv("../00 Data Retrieval and Cleaning/0_df_theoretical_ch_spot_price.csv") %>% mutate(date = ymd_hms(date))

regressors = c("day_ahead_price_de", "day_ahead_price_fr", "actual_load_ch", "capacity_forecast_de_lu_ch", "solar_ch" ,"crossborder_actual_flow_fr_ch", "nuclear_ch", "nuclear_actual_aggregated_de")
```

```{r}
target<- "day_ahead_price_ch"

pred <- predict_24_auto(df, target, regressors)

prediction_plots(target = target, predictions = pred, setting)

df_pred<- data.frame("date"= pred$date, 
             ".pred" = pred$predict,
             "actual" = pred$actual)

write.csv(df_pred, "../01 Task 1 - Spot Price/1 - ARIMAX - Prediction - CH - Data Theoretical/holdout_predictions.csv")


```

```{r}

fit<- inference(target, regressors = regressors, df = df)

inference_plots(df = df, fit = fit, target = target, setting)

```

### DE price

```{r}
df <- read.csv("../00 Data Retrieval and Cleaning/0_df_theoretical_ch_spot_price.csv") %>% mutate(date = ymd_hms(date))

regressors = c("biomass_actual_aggregated_de", "crossborder_actual_flow_de_lu_ch", "day_ahead_price_fr", "actual_load_de", "fossil_gas_actual_aggregated_de" ,"wind_onshore_actual_aggregated_de", "nuclear_actual_aggregated_de", "other_actual_aggregated_de", "solar_actual_aggregated_de")
```

```{r}
target<- "day_ahead_price_de"

pred <- predict_24_auto(df, target, regressors)

prediction_plots(target = target, predictions = pred, setting)

df_pred<- data.frame("date"= pred$date, 
             ".pred" = pred$predict,
             "actual" = pred$actual)

write.csv(df_pred, "../01 Task 1 - Spot Price/1 - ARIMAX - Prediction - DE - Data Theoretical/holdout_predictions.csv")
```

```{r}

fit<- inference(target, regressors = regressors, df = df)

inference_plots(df = df, fit = fit, target = target, setting)

```

### DECH price

```{r}
df <- read.csv("../00 Data Retrieval and Cleaning/0_df_theoretical_dech_auction_price.csv")%>% mutate(date = ymd_hms(date))


regressors = c("biomass_actual_aggregated_de", "crossborder_actual_flow_de_lu_ch", "day_ahead_price_fr", "actual_load_de", "fossil_gas_actual_aggregated_de" ,"wind_onshore_actual_aggregated_de", "nuclear_actual_aggregated_de", "other_actual_aggregated_de", "solar_actual_aggregated_de")
```

```{r}
target<- "auction_price_de_ch"

pred <- predict_24_auto(df, target, regressors)

pred$predict[pred$predict<0]<-0

prediction_plots(target = target, predictions = pred, setting)

df_pred<- data.frame("date"= pred$date, 
             ".pred" = pred$predict,
             "actual" = pred$actual)

write.csv(df_pred, "../02 Task 2 - Transmission Price/1 - ARIMAX - Prediction - DECH - Data Theoretical/holdout_predictions.csv")
```

```{r}

fit<- inference(target, regressors = regressors, df = df)

inference_plots(df = df, fit = fit, target = target, setting)

```

### CHDE price

```{r}
df <- read.csv("../00 Data Retrieval and Cleaning/0_df_theoretical_chde_auction_price.csv")%>% mutate(date = ymd_hms(date))


regressors = c("day_ahead_price_ch", "day_ahead_price_de", "actual_load_ch", "actual_load_de", "allocated_capacity_ch_de" ,"capacity_forecast_ch_de_lu", "crossborder_actual_flow_ch_de_lu", "solar_actual_aggregated_de", "nuclear_actual_aggregated_de", "solar_actual_aggregated_de")
```

```{r}
target<- "auction_price_ch_de"

pred <- predict_24_auto(df, target, regressors)

pred$predict[pred$predict<0]<-0

prediction_plots(target = target, predictions = pred, setting)

df_pred<- data.frame("date"= pred$date, 
             ".pred" = pred$predict,
             "actual" = pred$actual)

write.csv(df_pred, "../02 Task 2 - Transmission Price/1 - ARIMAX - Prediction - CHDE - Data Theoretical/holdout_predictions.csv")
```

```{r}

fit<- inference(target, regressors = regressors, df = df)

inference_plots(df = df, fit = fit, target = target, setting)

```