---
title: "Data Visualisation"
author: "Mathias Steilen"
date: "2024-03-12"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggsci)
library(scales)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# Default theme for charts
theme_set(
  theme_bw() +
    theme(  
      plot.title = element_text(face = "bold", size = 14),
      plot.subtitle = element_text(
        face = "italic", size = 10, colour = "grey50"
      ),
      plot.title.position = "plot"
    )
)

```

```{r}
# Read data
df = read_csv("../00_Data Retrieval and Cleaning/0_df_final_ch-de.csv") |> 
  mutate(date = ymd_hms(date)) |> 
  arrange(date)
```

### Chart 1: Day ahead price Switzerland

```{r}
# Make the chart
df |> 
  mutate(date = ymd_hms(date)) |> 
  filter(date(date) == ymd("2022-03-20")) |> 
  ggplot(aes(date, day_ahead_price_ch)) +
  geom_point() +
  geom_line() +
  scale_x_datetime(date_labels = "%H:%M") +
  labs(title = "Day-Ahead Prices",
       y = "", x= "") +
  theme(plot.margin = margin(10, 10, 10, 10))

ggsave("1_DA prices CH.png", width = 12, height = 6, dpi = 300,
       units = "cm")
```


### Chart 2: Swiss vs German Day-Ahead Prices

```{r}
df |> 
  mutate(date = ymd_hms(date)) |> 
  filter(date(date) == ymd("2022-03-20")) |> 
  select(date, day_ahead_price_ch, day_ahead_price_de) |> 
  pivot_longer(-date) |> 
  mutate(name = case_match(
    name, 
    "day_ahead_price_ch" ~ "Switzerland",
    "day_ahead_price_de" ~ "Germany",
  )) |> 
  ggplot(aes(date, value, colour = name)) +
  geom_point() +
  geom_line() +
  scale_x_datetime(date_labels = "%H:%M") +
  labs(title = "Day-Ahead Prices",
       subtitle = "20.03.2022",
       y = "", x= "") +
  ggsci::scale_colour_jama() +
  theme(plot.margin = margin(10, 10, 10, 10),
        legend.title = element_blank())

ggsave("2_DA prices DE CH.png", width = 16, height = 6, dpi = 300,
       units = "cm")
```

### Chart 3: Transfer Capacity

```{r}
df |>
  select(date, capacity_forecast_de_lu_ch, capacity_forecast_ch_de_lu) |> 
  mutate(date = floor_date(date, unit = "1 week")) |> 
  pivot_longer(-date) |> 
  mutate(name = case_match(
    name, 
    "capacity_forecast_de_lu_ch" ~ "DE to CH",
    "capacity_forecast_ch_de_lu" ~ "CH to DE",
  )) |> 
  group_by(date, name) |> 
  summarise(value = mean(value, na.rm = T)) |> 
  ggplot(aes(date, value, colour = name)) +
  geom_line() +
  labs(title = "Hourly Physical Transmission Capacity between Switzerland and Germany", 
       subtitle = "Binned averages by week",
       y = "Capacity", x = "", 
       colour = "Direction") +
  ggsci::scale_colour_jama() +
  scale_x_datetime(date_breaks = "1 year", date_labels = "%Y") +
  scale_y_continuous(labels = comma_format(suffix = " MW")) +
  theme(plot.margin = margin(10, 10, 10, 10),
        plot.title.position = "plot")


ggsave("3_Capacities over time.png", width = 20, height = 6, dpi = 300,
       units = "cm")
```

### Chart 4: Spread vs. Transmission Capacity

```{r}
# Read data
df = read_csv("../00_Data Retrieval and Cleaning/0_df_final_de-ch.csv") |> 
  mutate(date = ymd_hms(date)) |> 
  arrange(date)
```

```{r}
df |>
  transmute(date, auction_price, 
            spread = day_ahead_price_ch - day_ahead_price_de) |> 
  filter(date(date) >= ymd("2023-10-10"),
         date(date) <= ymd("2023-10-20")) |>
  pivot_longer(-date) |> 
  mutate(name = case_match(
    name, 
    "auction_price" ~ "JAO Price DE to CH",
    "spread" ~ "Spread CH - DE",
  )) |> 
  ggplot(aes(date, value, colour = name)) +
  geom_line() +
  labs(title = "Real World: Spread vs. Transmission Capacity Price", 
       subtitle = "They are not arbitrage free",
       y = "", x = "", 
       colour = "") +
  ggsci::scale_colour_jama() +
  scale_x_datetime(date_labels = "%d/%m/%Y") +
  scale_y_continuous(labels = comma_format(prefix = "EUR ")) +
  theme(plot.margin = margin(10, 10, 10, 10),
        plot.title.position = "plot")


ggsave("4_JAO vs Spread.png", width = 20, height = 6, dpi = 300,
       units = "cm")
```

### Chart 5: Germany vs Switzerland Spot Prices

```{r}
df |>
  transmute(date, day_ahead_price_ch, day_ahead_price_de) |> 
  pivot_longer(-date) |> 
  filter(date(date) >= ymd("2023-10-10"),
         date(date) <= ymd("2023-10-20")) |>
  mutate(name = case_match(
    name, 
    "day_ahead_price_ch" ~ "Switzerland",
    "day_ahead_price_de" ~ "Germany",
  )) |> 
  ggplot(aes(date, value, colour = name)) +
  geom_line() +
  # scale_x_datetime(date_labels = "%H:%M") +
  labs(title = "Day-Ahead Prices Switzerland and Germany",
       y = "", x= "") +
  scale_y_continuous(labels = comma_format(prefix = "CHF ")) +
  ggsci::scale_colour_jama() +
  theme(plot.margin = margin(10, 10, 10, 10),
        legend.title = element_blank(),
        plot.title.position = "plot",
        legend.position = "top")


ggsave("5_Spot.png", width = 28, height = 6.5, dpi = 300,
       units = "cm")
```

### Chart 6: Germany vs Switzerland spread

```{r}
df |>
  transmute(date, auction_price, 
            spread = day_ahead_price_ch - day_ahead_price_de) |> 
  filter(date(date) >= ymd("2023-10-10"),
         date(date) <= ymd("2023-10-20")) |>
  ggplot(aes(date, spread)) +
  geom_line() +
  labs(title = "Spread in Day-Ahead Spot Price Switzerland - Germany", 
       y = "Spread", x = "", 
       colour = "") +
  ggsci::scale_colour_jama() +
  scale_x_datetime(date_labels = "%d/%m/%Y") +
  scale_y_continuous(labels = comma_format(prefix = "EUR ")) +
  theme(plot.margin = margin(10, 10, 10, 10),
        plot.title.position = "plot")

ggsave("6_Spread.png", width = 28, height = 5, dpi = 300,
       units = "cm")
```

```{r}
ggsave("6_Spread large.png", width = 28, height = 8, dpi = 300,
       units = "cm")
```


### Chart 7: JAO Prices

```{r}
auction_prices = read_csv("../00_Data Retrieval and Cleaning/0_df_final_de-ch.csv") |> 
  mutate(date = ymd_hms(date)) |> 
  arrange(date) |> 
  select(date, de_ch = auction_price) |> 
  left_join(
    read_csv("../00_Data Retrieval and Cleaning/0_df_final_ch-de.csv") |> 
      mutate(date = ymd_hms(date)) |> 
      arrange(date) |> 
      transmute(date, ch_de = auction_price),
    by = "date"
  ) 

auction_prices |> 
  filter(date(date) >= ymd("2024-01-01")) |> 
  pivot_longer(-date) |> 
  mutate(name = case_match(
    name, 
    "de_ch" ~ "DE to CH",
    "ch_de" ~ "CH to DE",
  )) |> 
  ggplot(aes(date, value, colour = name)) +
  geom_line() +
  labs(title = "JAO Transmission Capacity Prices", 
       y = "CHF/MW", x = "", 
       colour = "") +
  ggsci::scale_colour_jama() +
  scale_x_datetime(date_labels = "%d/%m/%Y") +
  scale_y_continuous(labels = comma_format(prefix = "EUR ")) +
  theme(plot.margin = margin(10, 10, 10, 10),
        plot.title.position = "plot")

ggsave("7_Jao prices.png", width = 15, height = 7, dpi = 300,
       units = "cm")
```

