---
title: "fastTS_de_ch"
author: "Federico Deotto"
date: "2024-05-15"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)

library(ggplot2)
library(lubridate)
library(readr)
library(purrr)
library(stringr)
library(tidyr)
library(ggsci)
library(scales)
library(fastTS)
library(dplyr)
library(xts)
library(tibble)
library(sfsmisc)




setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
source('builtin_functions.R')

# Default theme for charts
theme_set(
  theme_bw() +
    theme(  
      plot.title = element_text(face = "bold", size = 14),
      plot.subtitle = element_text(
        face = "italic", size = 10, colour = "green50"
      )
    )
)
```


# Swiss Price
```{r}
time_cut <- as.POSIXct("2023-01-01 00:00:00", tz = "UTC")
df <- read_csv("../00 Data Retrieval and Cleaning/0_df_predictive_dech_auction_price.csv") %>% 
  filter(date >= time_cut)


dummies_columns <- df %>%
  select(contains(c("_dummy", "cal_"))) %>% 
  colnames()

factor_colums <- c('dst', dummies_columns)

df <- df %>%                              #needed for recovering interaction easily
  mutate_at(vars(factor_colums), factor)

x <- df %>%
  select(contains(c('cal_', 'dst')))

formula_str <- paste("~ dst +",
                     paste(names(x)[-which(names(x) == "dst")], " * dst", sep = "", collapse = " + "), sep = "")
formula_str <- formula(formula_str)

x <- model.matrix(formula_str, data = x) %>%
  as_tibble() %>%
  select(-contains("Intercept")) %>% 
  mutate_all(., as.factor)

cond <- x %>%
  mutate_all(as.numeric) %>% 
  apply(., 2, function(x) all(x == 1))

omit_names <- colnames(x)[cond]

x <- x %>% 
  select(-omit_names)

df <- df %>% 
  select(-contains(c('cal_', 'dst'))) %>% 
  bind_cols(., x)

rm(x)

discontinue_variables <- df %>% 
  select(where(is.numeric)) %>% 
  slice(1700:1900) %>%     #easy for compuattion to subset
  detect_columns_with_consecutive(n_consecutive = 13) %>%
  select(-c(allocated_capacity_ch_de, allocated_capacity_de_ch)) %>% 
  select(-contains('forecast')) %>% 
  names()


df <- df %>%
  mutate(across(all_of(discontinue_variables), ~ interpolation_vector(.))) #they will be the same for all type and price

df <- df %>%  
  mutate(across(-date, as.numeric))

variances = df %>%  
  select(-c(date)) %>%  
  apply(2, var)

null_variance_cols <- names(variances[variances == 0])
df <- df %>% 
  select(-all_of(null_variance_cols))

redundant_columns <- lm(auction_price_de_ch ~ ., data = df) %>%  
  broom::tidy() |> 
  filter(is.na(estimate)) %>% 
  pull(term) %>%
  str_remove_all('`')

df <- df %>% 
  select(-all_of(redundant_columns))

n <- df  %>% 
  nrow()

x <- df  %>% 
  filter(date >= as.POSIXct("2024-01-01 00:00:00", tz = "UTC")) %>% 
  nrow()

p.train <- 1-(x/n)
max_lag =24*5   # 1 month - this is the amount of data that we will lose by shifting


rm(x, n)

dummies_columns <- c( 'dst', 'cal', 'dummy', 'date')

ff <- formula(auction_price_de_ch ~ -1 + .^2) #only numeric
X1 <- df %>% 
  select(-contains(dummies_columns)) %>% 
  model.matrix(ff, data = .)


X2 <- df %>%
  select(-c(auction_price_de_ch, date)) %>% 
  select(-contains(dummies_columns)) %>% 
  mutate(across(everything(), ~ .^2, .names = "{.col}_squared")) %>% 
  select(contains('_squared'))

df <- df %>% 
  select(c(auction_price_de_ch, date)) %>% 
  bind_cols(., X1) %>% 
  bind_cols(., X2)


rm(X1, X2)
```


```{r, cache=TRUE}
df %>% 
  ggplot(aes(date))+
  geom_line(aes(y = auction_price_ch_de))+
  labs(title = 'Price original', x = 'Date', y = 'Price')

df %>% 
  ggplot(aes(date))+
  geom_line(aes(y = ihs10(auction_price_ch_de)))+
  labs(title = 'Price ihs10', x = 'Date', y = 'Price')

df %>% 
  mutate(auction_price_ch_de = log(auction_price_ch_de - min(auction_price_ch_de) +1)) %>% 
  ggplot(aes(date))+
  geom_line(aes(y = auction_price_ch_de))+
  labs(title = 'Price log', x = 'Date', y = 'Price')

df %>% 
  mutate(auction_price_ch_de = u.log(auction_price_ch_de)) %>% 
  ggplot(aes(date))+
  geom_line(aes(y = auction_price_ch_de))+
  labs(title = 'Price u.log', x = 'Date', y = 'Price')

df %>% 
  mutate(auction_price_ch_de = asinh(auction_price_ch_de)) %>% 
  ggplot(aes(date))+
  geom_line(aes(y = auction_price_ch_de))+
  labs(title = 'Price tanh', x = 'Date', y = 'Price')
```

```{r}
models <- df %>% 
  mutate(auction_price_de_ch = ihs10(auction_price_de_ch)) %>% 
  model_list(p.train = p.train, n_lags_max = max_lag, response = 'auction_price_de_ch')
```

```{r}
best_models <- model_selected(models)
```

```{r}
results <- prediction_step(models, auction = T, inverse_transformation = inverse_ihs10)
```

# Swiss Price
```{r}
time_cut <- as.POSIXct("2023-01-01 00:00:00", tz = "UTC")

df <- read_csv("../00 Data Retrieval and Cleaning/0_df_theoretical_dech_auction_price.csv") %>% 
  filter(date >= time_cut)


dummies_columns <- df %>%
  select(contains(c("_dummy", "cal_"))) %>% 
  colnames()

factor_colums <- c('dst', dummies_columns)

df <- df %>%                              #needed for recovering interaction easily
  mutate_at(vars(factor_colums), factor)

x <- df %>%
  select(contains(c('cal_', 'dst')))

formula_str <- paste("~ dst +",
                     paste(names(x)[-which(names(x) == "dst")], " * dst", sep = "", collapse = " + "), sep = "")
formula_str <- formula(formula_str)

x <- model.matrix(formula_str, data = x) %>%
  as_tibble() %>%
  select(-contains("Intercept")) %>% 
  mutate_all(., as.factor)

cond <- x %>%
  mutate_all(as.numeric) %>% 
  apply(., 2, function(x) all(x == 1))

omit_names <- colnames(x)[cond]

x <- x %>% 
  select(-omit_names)

df <- df %>% 
  select(-contains(c('cal_', 'dst'))) %>% 
  bind_cols(., x)

rm(x)

discontinue_variables <- df %>% 
  select(where(is.numeric)) %>% 
  slice(1700:1900) %>%     #easy for compuattion to subset
  detect_columns_with_consecutive(n_consecutive = 13) %>%
  select(-c(allocated_capacity_ch_de, allocated_capacity_de_ch)) %>% 
  select(-contains('forecast')) %>% 
  names()


df <- df %>%
  mutate(across(all_of(discontinue_variables), ~ interpolation_vector(.))) #they will be the same for all type and price

df <- df %>%  
  mutate(across(-date, as.numeric))

variances = df %>%  
  select(-c(date)) %>%  
  apply(2, var)

null_variance_cols <- names(variances[variances == 0])
df <- df %>% 
  select(-all_of(null_variance_cols))

redundant_columns <- lm(auction_price_de_ch ~ ., data = df) %>%  
  broom::tidy() |> 
  filter(is.na(estimate)) %>% 
  pull(term) %>%
  str_remove_all('`')

df <- df %>% 
  select(-all_of(redundant_columns))

n <- df  %>% 
  nrow()

x <- df  %>% 
  filter(date >= as.POSIXct("2024-01-01 00:00:00", tz = "UTC")) %>% 
  nrow()

p.train <- 1-(x/n)
max_lag =24*5   # 1 month - this is the amount of data that we will lose by shifting


rm(x, n)

dummies_columns <- c( 'dst', 'cal', 'dummy', 'date')

ff <- formula(auction_price_de_ch ~ -1 + .^2) #only numeric
X1 <- df %>% 
  select(-contains(dummies_columns)) %>% 
  model.matrix(ff, data = .)


X2 <- df %>%
  select(-c(auction_price_de_ch, date)) %>% 
  select(-contains(dummies_columns)) %>% 
  mutate(across(everything(), ~ .^2, .names = "{.col}_squared")) %>% 
  select(contains('_squared'))

df <- df %>% 
  select(c(auction_price_de_ch, date)) %>% 
  bind_cols(., X1) %>% 
  bind_cols(., X2)


rm(X1, X2)
```

```{r}
models <- df %>% 
  mutate(auction_price_de_ch = ihs10(auction_price_de_ch)) %>% 
  model_list(p.train = p.train, n_lags_max = max_lag, response = 'auction_price_de_ch')
```

```{r}
best_models <- model_selected(models)
```

```{r}
results <- prediction_step(models, auction = T, inverse_transformation = inverse_ihs10)
```