---
title: "Auction rices CH_DE"
author: "Olivier Zehnder"
date: "2024-05-21"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fGarch)
```


```{r}
df_auct <- read.csv("~/Downloads/0_df_theoretical_dech_auction_price.csv", header=TRUE)



df_auct$cal_day_in_month = as.factor(df_auct$cal_day_in_month)
df_auct$cal_day_in_week = as.factor(df_auct$cal_day_in_week)
df_auct$cal_hour_in_day= as.factor(df_auct$cal_hour_in_day)
df_auct$cal_month = as.factor(df_auct$cal_month)
df_auct$cal_quarter = as.factor(df_auct$cal_quarter)
df_auct$cal_year = as.factor(df_auct$cal_year)



df_auct_train= arrange(df_auct, date)[1:8734,]
df_auct_test= arrange(df_auct, date)[8735:9477,]
```


```{r}

# Prepare your data
response <- df_auct_train$auction_price_de_ch
external_regressors <- df_auct_train[, c("day_ahead_price_de", "day_ahead_price_at")]  # Replace with your actual regressor names

# Combine response and regressors into one data frame
df_combined <- cbind(response, external_regressors)

garch_model <- garchFit(formula = ~ arma(1, 1) + garch(1, 1),
                        data = response,  # Provide the entire data frame
                        trace = FALSE)

# Print the summary of the model
summary(garch_model)


```


```{r}
prediction_horizon= 24
forecast_values <- predict(garch_model, n.ahead = prediction_horizon)
response_test= df_auct_test$auction_price_de_ch[0:prediction_horizon]

#Plotting out of sample performance
plot(response_test, type="l", main="German Day Ahead Prices - Predictions",  xlab = " ", ylab = "Price", xaxt = "n", ylim=c(0,350))
lines(forecast_values$meanForecast, col="red")
axis(1, at = seq(1, 743, by = 360), labels = df_auct_test$date[seq(1, 743, by = 360)], las = 2, cex.axis = 0.7)
```


```{r}

# Initialize the training data
df_combined <- df_auct_train  # Assuming this data frame includes all necessary variables

# Define prediction horizon
prediction_horizon <- 24

# Initialize a list to store forecasts
all_forecasts <- c()

i=1
# Loop through each 24-hour period in your test dataset
for (k in seq(1:nrow(df_auct_test))) {
    if (i + prediction_horizon > nrow(df_auct_test)) {
        break  # Avoid running out of data
    }
  print(i)
    print("check 1")
  
    # Fit GARCH model
    response <- df_combined$auction_price_de_ch
    #external_regressors <- df_combined[, c("day_ahead_price_ch", "day_ahead_price_at")]
    garch_model <- garchFit(formula = ~ arma(2, 2) + garch(1, 1),
                            data = response,  # Use only the response for the GARCH model
                            trace = FALSE)
  print("check 2")
    # Predict the next 24 hours
    forecast <- predict(garch_model, n.ahead = prediction_horizon)
    all_forecasts=c(all_forecasts,forecast$meanForecast)
    # Add actual values for the next 24 hours to the training data
    new_data <- df_auct_test[i:(i + prediction_horizon - 1), ]
    df_combined <- rbind(df_combined, new_data)
  print("check 3")
    # Increment by prediction horizon for the next iteration
    i <- i + prediction_horizon
}

# Now, all_forecasts contains all the prediction results

```

```{r}
prediction_horizon= length(all_forecasts)
forecast_values <- all_forecasts
response_test= df_auct_test$auction_price_de_ch[0:prediction_horizon]

#Plotting out of sample performance
plot(response_test, type="l", main="Swiss Day Ahead Prices - Predictions",  xlab = " ", ylab = "Price", xaxt = "n", ylim=c(0,350))
lines(forecast_values, col="red")
axis(1, at = seq(1, 743, by = 360), labels = df_auct_test$date[seq(1, 743, by = 360)], las = 2, cex.axis = 0.7)
```


```{r}
library(yardstick)
rsquared= rsq_vec(as.numeric(response_test),as.numeric(forecast_values))
rmse=  sqrt(mean((response_test -forecast_values)^2))
MAE= mean(response_test -forecast_values)
```

```{r}

df_scores= data.frame(date= df_auct_test$date[1:720], .pred= forecast_values, acutal=response_test )

# Assuming 'df' is your dataframe
write.csv(df_scores, "/Users/olivier/Documents/ETH 2. Semester¨/Statslab/Scores Auction prices/1 - GARCH - Prediction - DECH - Data Theoretical/holdout_predictions.csv", row.names = FALSE)


print("saved")

```
